### ISSUE TITLE
PluginError: Error with plugin "highlight": Cannot find module 'highlight.js'

### ISSUE THREAD

**Issue by tuchida** [GitbookIO/gitbook#1834]
Thank you for giving us your feedback! We listed some guidelines to help you:

If possible, open separate issues for each bug report. Avoid grouping bugs that are unrelated.

### What is the current behavior?

If the current behavior is a bug, please provide the steps to reproduce. if possible, provide the GitBook version being used (`gitbook -V`) and the system infromations (OS and version).

```sh
$ ./node_modules/.bin/gitbook -V
CLI version: 2.3.2
GitBook version: 3.2.3
```

`gitbook serve` works in version 3.2.2.
```sh
$ ./node_modules/.bin/gitbook serve docs/ --gitbook=3.2.2
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 8 plugins are installed 
info: 6 explicitly listed 
info: loading plugin "search-languages"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 12 pages 
info: found 10 asset files 
info: >> generation finished with success in 1.0s ! 

Starting server ...
Serving book on http://localhost:4000
```

But it can't work in 3.2.3.
```sh
$ ./node_modules/.bin/gitbook serve docs/ --gitbook=3.2.3
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 8 plugins are installed 
info: 6 explicitly listed 
info: loading plugin "search-languages"... OK 
info: loading plugin "highlight"... ERROR

PluginError: Error with plugin "highlight": Cannot find module 'highlight.js'
```

book.json:
```json
{
    "plugins": [
        "-lunr",
        "search-languages",
        "-livereload"
    ],
    "pluginsConfig": {
        "searchLanguages": {
            "lang": "jp"
        }
    }
}
```

### What is the expected behavior?

How do you think, or how would you like it should behave.

It can work in 3.2.3.

#### For GitBook.com

Provide, if possible, your username and the URL of the concerned book.

----

The GitBook Team

**Comment by kogai** [comment]
Same issue occurred for my environment.

```
./node_modules/.bin/gitbook -V
CLI version: 2.3.2
GitBook version: 3.2.3
```

**Comment by chriscapetown** [comment]
Same here, not sure what going on

**Comment by kavolorn** [comment]
I have the same issue with not being able to push my builds to heroku. 

There is about 70-80% probability that I end up with `PluginError: Error with plugin "highlight": Cannot find module 'highlight.js'` error.

I did not find any solution or advice. I every time push to heroku until its passing. Thats terrible and destroys any automation.

Could there be any timings which we can configure for plugin installer or something similar?

**Comment by dylanmoz** [comment]
I've been having the same issue, still happening on 3.2.2

**Comment by saito-tom** [comment]
I also encountered the same problem with v3.2.3.
This problem seems to be caused by the difference of `highlight.js/package.json`. (The concrete path is `~/.gitbook/versions/3.2.3/node_modules/gitbook-plugin-highlight/node_modules/highligh
t.js/package.json`)

When this problem occurred, package.json in highlight.js was very short and had only 30 rows. Also, it did not contain the top level `main` property.
In v3.2.2, the code of nodejs `JSON.parse(json).main` succeeded because the `main` property was present in package.json, but it fails in v3.2.3 because there is no `main`.
https://github.com/nodejs/node/blob/3e144496d3ebe992a0f045f169a23980dd4b5396/lib/module.js#L124
The build succeeded when I added `"main": "./lib/index.js"` to v3.2.3 `highlight.js/package.json`.

After deleting `~/.gitbook` and reinstalling it, `highlight.js/package.json` of v.3.2.3 is also the same as v3.2.2, and the problem no longer reproduces.
In other environments this problem occurred in v 3.2.2, so it seems that it is not limited to v3.2.3.

I could not find the reason for shortening package.json.

`highlight.js/package.json` when the problem occurred.
```
{
  "name": "highlight.js",
  "version": "9.2.0",
  "devDependencies": {
    "bluebird": "^3.0.1",
    "commander": "^2.3.0",
    "del": "^2.0.2",
    "gear": "^0.9.4",
    "gear-lib": "^0.9.2",
    "glob": "^6.0.1",
    "jsdom": "7.0.2",
    "lodash": "^4.0.0",
    "mocha": "^2.0.1",
    "should": "^8.1.1",
    "tiny-worker": "^1.1.1",
    "js-beautify": "^1.5.10"
  },
  "directories": {},
  "dist": {
    "shasum": "0d4ef61279c4067da55edf8976f1b9f28f69f202",
    "tarball": "https://registry.npmjs.org/highlight.js/-/highlight.js-9.2.0.tgz"
  },
  "engines": {
    "node": "*"
  },
  "_hasShrinkwrap": false,
  "_shasum": "0d4ef61279c4067da55edf8976f1b9f28f69f202",
  "_resolved": "https://registry.npmjs.org/highlight.js/-/highlight.js-9.2.0.tgz",
  "_from": "highlight.js@9.2.0"
}
```

**Comment by saito-tom** [comment]
I tried the following workaround and I have successfully avoided the problem.

For your computer, package.json seems to be broken randomly at installation, so delete `~/.gitbook` and fix it by `gitbook install`.
For CI, you can keep the state installed correctly by caching `~/.gitbook`. I used CircleCI so I could cache installed gitbook.

I wanted to find out why an incorrect package.json appeared, but I gave up because I do not reproduce easily.

**Comment by cpsubrian** [comment]
This same problem is biting me in CD (Netlify deploying my gitbook). I don't have the ability to cache `.gitbook` there, so need to figure out some other workaround.

**Comment by i8ramin** [comment]
Any updates on this one?

**Comment by d4rky-pl** [comment]
This issue makes gitbook unusable on any automated deployment.

**Comment by Charliemowood** [comment]
I am trying to use gitbook-cli version 2.3.2. Using to install dependencies. Getting this error about 50% of the time in CI (travis).

**Comment by d4rky-pl** [comment]
@Charliemowood try forcing npm version to 3.x in package.json, I think it helped a bit, though I just gave up at this point and started rebuilding on git precommit hook (using husky)

**Comment by Charliemowood** [comment]
From the GitBook slack, it seems that it may well be a npm issue ultimately. Create a cache seems the logical next step.

**Comment by d4rky-pl** [comment]
I'd say stopping relying on non-standard mechanisms and bundling custom npm instead of relying on node_modules and normal package resolution seems like a way better idea.

**Comment by EdwardDrapkin** [comment]
I ran into this issue as well and brute forced it on CI:

```bash

yarn gitbook install && yarn gitbook install docs/

yarn gitbook build docs/ /book/

while [ "$?" != "0" ]; do
        rm -rf ~/.gitbook &&
        yarn gitbook install &&
        yarn gitbook install docs/ &&
        yarn gitbook build docs/ /book/
done
```

**Comment by Charliemowood** [comment]
The cache solution seems to have worked just saving and using a working `~/.gitbook`.

**Comment by colmonty** [comment]
I'm also getting this error. Would downgrading the CLI in my package.json help here? Are the plugins NPM modules themselves and hence would explicitly listing/installing them via yarn/npm help?

**Comment by thovden** [comment]
I got this error using node 6 / npm 3. Seems to be resolved with node 8 / npm 5.

**Comment by johnloy** [comment]
Just another "me too" here.

**Comment by dbackeus** [comment]
#metoo

**Comment by jschr** [comment]
Extremely annoying issue, here's the workaround I came up with which works in CI without needing to cache or retry installing:

1. Install `highlight.js` as a project dependency.
2. Install gitbook
3. Copy the local `node_modules/highlight.js` to `~/.gitbook`
4. Build gitbook

Full CI script:

```bash
#!/bin/bash

# Install gitbook
yarn gitbook install
# Copy the local highlight.js to gitbook's node_modules.
cp -a node_modules/highlight.js/. ~/.gitbook/versions/3.2.3/node_modules/highlight.js/
# Build docs
yarn gitbook build
```
