### ISSUE TITLE
error in using gitbook init

### ISSUE THREAD

**Issue by harwinvoid** [GitbookIO/gitbook#1818]
I install the latest version of gitbook-cli@3.2.2, but i get a  error like below:
```
➜  workspace gitbook init
Error loading version latest: Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/harwin/.gitbook/versions/3.2.2/lib/index.js:1:76)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

TypeError: Cannot read property 'commands' of null
```
my node js version and npm version is:
```
➜  workspace npm -v
3.10.10
➜  workspace node -v
v6.11.0
```

**Comment by oblador** [comment]
Getting the same issue with on both node 7, 8 and with both yarn and npm.

**Comment by sargant** [comment]
I'm also having the same issue on multiple different platform configurations:

node@6.11.1 npm@3.10.10 gitbook-cli@2.3.1 -> running `gitbook init` gives the same error
node@8.1.3 npm@5.0.3 gitbook@2.3.1 -> running `gitbook init` gives the same error

**Comment by birkskyum** [comment]
Same here with:
node@8.1.4
npm@5.0.3

**Comment by grmpyninja** [comment]
It's not only with `gitbook init` but with other commands as well.

Tried to use this docker <https://hub.docker.com/r/fellah/gitbook/> and I switched between node:6-slim, 8-slim and full 8 and same error while `gitbook build` as well as `gitbook serve`

**Comment by AaronO** [comment]
@harwinvoid @grmpyninja @oblador @sargant @birkskyum This seems to a regression in `gitbook-cli@2.3.1` caused by https://github.com/GitbookIO/gitbook-cli/pull/60

**Comment by birkskyum** [comment]
Downgrading to 2.3.0 doesn't seem to fix the issue.

**Comment by oblador** [comment]
`cd ~/.gitbook/versions/3.2.2 && npm i` solved it for me

**Comment by birkskyum** [comment]
Great! It solved it for both @2.3.0 and @2.3.1

**Comment by saun4app** [comment]
Thanks to @oblador, `cd ~/.gitbook/versions/3.2.2 && npm i` fixed the issue for `gitbook init`.  Howver, I still get the same error message for `gitbook serve` and `gitbook build`.

**Comment by AaronO** [comment]
@oblador Thanks for posting that workaround, but ideally we should get it fixed in the core.

It seems like `npm@5` no longer installs or can be used as a lib to install deps as we expect it to (and that worked with `npm@3`).

**Comment by cpsubrian** [comment]
Reverting to 2.3.0 worked for me (in Netlify CI environment).

**Comment by adiferd** [comment]
I got the same error on Arch linux
```
Node version v.8.1.2
CLI version 2.3.1
gitbook version 3.2.2
```

```
$ gitbook init
```

Error Message
```
Error loading version latest: Error: Cannot find module 'extend'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/af/.gitbook/versions/3.2.2/lib/index.js:1:76)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

TypeError: Cannot read property 'commands' of null
```

**Comment by AaronO** [comment]
This should now be fixed by the `gitbook-cli` @ `2.3.2` release and is a duplciate of https://github.com/GitbookIO/gitbook-cli/issues/68

**Comment by winniehell** [comment]
Thank you @AaronO! :heart: I can confirm this is fixed in 2.3.2. :sparkles:

**Comment by adiferd** [comment]
Thank you @AaronO
